### ISSUE TITLE
建议增加 当前状态、ACC状态。我自己已经修改完成。

### ISSUE THREAD

**Issue by H-BL** [dscao/cloud_gps#1]
![1](https://github.com/dscao/cloud_gps/assets/66126594/8e42dc77-e72c-41a6-8eec-296ef97a3811)
当前状态取 runorstop;
ACC状态取 acc

对于nr里面调用车辆状态所用。

**Comment by dscao** [comment]
这些如果可用会在device_tracker实体的属性出现，属性的值在自动化或nodered都可以调用的。如果想在实体状态中显示可以自己通过模板创建实体。如果某些平台不可用，则不会显示。所有没有加入是否显示的传感器实体选项。

**Comment by H-BL** [comment]
可能是我不会在nodered里面调用属性吧，是有属性的。所以我才修改了集成 新增了两个实体。希望下次发版可以加入  哈哈哈怕更新了以后 我还要再改集成。辛苦大佬了。

**Comment by H-BL** [comment]
还有一个问题就是，新增集成以后 实体名称是imei，右上角修改名称后，如果是两个设备的话 有一个的实体名称会变成 unknown，虽然不影响使用，但是 只要不点击一起修改实体名称，就不会影响了。可能是我不会使用吧。
